name: deploy-preview

on:
  workflow_run:
    workflows:
      - check-pr-owner-is-fte
    types: 
      - completed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: PR checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Deploy preview site
      uses: cssjpn/blog-gh-actions/deploy-preview@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        azure-storage-connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        preview-base-url: "https://jpazureidblogstorage.z5.web.core.windows.net/"

