name: check-pr-owner-is-fte

on: [pull_request]
jobs:
  ok-to-preview-fte:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - run: sleep 5
    - name: Check PR owner is FTE
      id: check_pr_owner_is_fte
      run: |
        federated_token=`curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value'`
        username="${{ github.event.pull_request.head.repo.owner.login }}"
        aad_username=`curl -H "Authorization: Bearer $federated_token" -H "Workflow run-on-main-branch" https://jpcssblogdev.azurewebsites.net/api/githublinks/$username | jq -r '.alias'`
        if [ -z "$aad_username" ]; then
          echo "${username} is not Microsoft linked account. username: ${aad_username}"
          exit 1
        else
          echo "${username} is Microsoft linked account. username: ${aad_username}"
        fi
